syntax = "proto3";

package ralvarezdev;

import "google/protobuf/empty.proto";

service Certificate {
    rpc IssueCertificate(IssueCertificateRequest) returns (stream IssueCertificateResponse);
    rpc ValidateCertificate(stream ValidateCertificateRequest) returns (ValidateCertificateResponse);
    rpc RevokeCertificate(RevokeCertificateRequest) returns (google.protobuf.Empty);
}

message IssueCertificateRequest {
  string common_name = 1;
  string organization = 2;
  string organizational_unit = 3;
  string locality = 4;
  string state = 5;
  string country = 6;
  bytes public_key = 7;
}

message IssueCertificateResponse {
    bytes content = 1;
}

message ValidateCertificateRequest {
    bytes certificate = 1;
}

message ValidateCertificateResponse {
    bool is_valid = 1;
    optional string details = 2;
}

message GetPublicKeyRequest {
    string common_name = 1;
}

message GetPublicKeyResponse {
    bytes public_key = 1;
}

message RevokeCertificateRequest {
    string serial_number = 1;
}