syntax = "proto3";

package ralvarezdev;

import "google/protobuf/empty.proto";

service Certificate {
    rpc IssueCertificate(IssueCertificateRequest) returns (stream IssueCertificateResponse);
    rpc ValidateCertificate(stream ValidateCertificateRequest) returns (google.protobuf.Empty);
    rpc RevokeCertificate(RevokeCertificateRequest) returns (google.protobuf.Empty);
    rpc GetPublicKeyByCommonName(GetPublicKeyByCommonNameRequest) returns (GetPublicKeyByCommonNameResponse);
}

message IssueCertificateRequest {
  string common_name = 1;
  string organization = 2;
  string organizational_unit = 3;
  string locality = 4;
  string state = 5;
  string country = 6;
  bytes public_key = 7;
}

message IssueCertificateResponse {
    bytes certificate_content = 1;
}

message ValidateCertificateRequest {
    bytes certificate_content = 1;
}

message RevokeCertificateRequest {
    string serial_number = 1;
}

message GetPublicKeyByCommonNameRequest {
    string common_name = 1;
}

message GetPublicKeyByCommonNameResponse {
    bytes public_key = 1;
}