syntax = "proto3";

package ralvarezdev;

service Certificate {
    rpc GenerateCertificate(GenerateCertificateRequest) returns (stream GenerateCertificateResponse);
    rpc ValidateCertificate(stream ValidateCertificateRequest) returns (ValidateCertificateResponse);
    rpc GetPublicKey(GetPublicKeyRequest) returns (GetPublicKeyResponse);
}

message GenerateCertificateRequest {
  string common_name = 1;
  string organization = 2;
  string organizational_unit = 3;
  string locality = 4;
  string state = 5;
  string country = 6;
  bytes public_key = 7;
}

message GenerateCertificateResponse {
    bytes content = 1;
}

message ValidateCertificateRequest {
    bytes certificate = 1;
}

message ValidateCertificateResponse {
    bool is_valid = 1;
}

message GetPublicKeyRequest {
    string common_name = 1;
}

message GetPublicKeyResponse {
    bytes public_key = 1;
}